# Netlify configuration for Interview Teleprompter

[build]
  publish = "."
  command = "" # Statutory site, no build command needed
  functions = "netlify/functions"

[context.production]
  # Settings for the production branch ('master')

[context.dev]
  # Specific settings for the 'dev' branch
  # Tell robots not to index our dev branch
  [[context.dev.headers]]
    for = "/*"
    [context.dev.headers.values]
      X-Robots-Tag = "noindex"

[context.branch-deploy]
  # For ALL other non-production branches
